security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        anonymous: ~
        logout: ~
        guard:
          authenticators:
            - App\Security\TokenAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/users/authentication, methods: POST, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/categories, methods: POST, roles: [ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/api/, roles: ROLE_USER }

